---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service
  labels:
    app: comment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment-service
  template:
    metadata:
      labels:
        app: comment-service
    spec:
      containers:
        - name: comment-service
          image: SadditS6.azurecr.io/comment-service:v0.2.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
            - containerPort: 5003
          envFrom:
            - configMapRef:
                name: comment-env
---
apiVersion: v1
kind: Service
metadata:
  name: comment-service
spec:
  selector:
    app: comment-service
  ports:
    - protocol: TCP
      port: 5003
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: comment-service-ingress
spec:
  rules:
    - http:
        paths:
          - path: /comment-service
            pathType: Prefix
            backend:
              service:
                name: comment-service
                port:
                  number: 80
