version: "3.9"

services:
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    hostname: rabbitmq
    labels:
      NAME: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    env_file:
      - ./docker/rabbitmq.env

  mysql-db:
    container_name: mysqlDb
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  gateway:
    container_name: gateway
    image: gateway
    restart: always
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - user-service
      - post-service
      - comment-service
      - mysql-db
      - rabbitmq

  user-service:
    depends_on: ["mysql-db", "rabbitmq"]
    container_name: userService
    image: user-service
    restart: unless-stopped
    build:
      context: ./services/user-service
    ports:
      - "8877:8877"

  # post-service:
  #   container_name: postService
  #   image: post-service
  #   restart: always
  #   build:
  #     context: ./services/post-service
  #   ports:
  #     - "8879:8879"
  #   depends_on:
  #     - mysql-db

  # comment-service:
  #   container_name: commentService
  #   image: comment-service
  #   restart: always
  #   build:
  #     context: ./services/comment-service
  #   ports:
  #     - "8880:8880"
  #   depends_on:
  #     - mysql-db

volumes:
  my-db:
    driver: local
  rabbitmq-data:
    driver: local
