version: "3.9"

services:
  mysql-db:
    container_name: mysqlDb
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./docker:/docker-entrypoint-initdb.d:z

  gateway:
    container_name: gateway
    image: gateway
    restart: always
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - user-service
      - post-service
      - comment-service
      # - authorization-service

  user-service:
    container_name: userService
    image: user-service
    restart: always
    build:
      context: ./services/user-service
    ports:
      - "8877:8877"
    depends_on:
      - mysql-db

  post-service:
    container_name: postService
    image: post-service
    restart: always
    build:
      context: ./services/post-service
    ports:
      - "8879:8879"
    depends_on:
      - mysql-db

  comment-service:
    container_name: commentService
    image: comment-service
    restart: always
    build:
      context: ./services/comment-service
    ports:
      - "8880:8880"
    depends_on:
      - mysql-db

  # authorization-service:
  #   container_name: authorizationService
  #   image: authorization-service
  #   restart: always
  #   build:
  #     context: ./services/authorization-service
  #   ports:
  #     - "8878:8878"
  #   depends_on:
  #     - mysql-db

volumes:
  SadditMySQLVolume:
    driver: local
