---
name: Azure Deployment Test CI
on:
  push:
    # paths:
    #   - "src/Frontend/saddit-front/**"
    branches:
      - master
      - develop
      - feature/**
  pull_request:
    branches: [master]

env:
  REGISTRY_NAME: SadditS6
  CLUSTER_NAME: SadditS6
  CLUSTER_RESOURCE_GROUP: saddit-resource-group
  APP_NAME: frontend-saddit

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      # Connect to Azure Container Registry (ACR)
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Container build and push to a Azure Container Registry (ACR)
      - run: |
          docker build -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:v0.1.1 ./src/Frontend/saddit-front
          docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:v0.1.1
