name: Frontend CI

on:
  push:
    paths:
      - "src/Frontend/saddit-front/**"
    branches:
      - develop
      - feature/**
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build stage

    defaults:
      run:
        working-directory: "./src/Frontend/saddit-front"

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: "yarn"
          cache-dependency-path: ./src/Frontend/saddit-front/yarn.lock

      - name: Run build
        working-directory: src/Frontend/saddit-front
        run: yarn

  test:
    runs-on: ubuntu-latest
    name: Test stage
    needs: build

    defaults:
      run:
        working-directory: "./src/Frontend/saddit-front"

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: "yarn"
          cache-dependency-path: ./src/Frontend/saddit-front/yarn.lock

      - name: Run build
        working-directory: src/Frontend/saddit-front
        run: yarn

      - name: Run Tests
        working-directory: src/Frontend/saddit-front
        run: yarn test

  zap_scan:
    runs-on: ubuntu-latest
    name: Scan web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: "https://i399015.hera.fhict.nl/"
          rules_file_name: ".zap/rules.tsv"
          cmd_options: "-a"
