name: Frontend CI - Tests

on:
  push:
    paths:
      - "src/Frontend/saddit-front/**"
    branches:
      - master
      - develop
      - feature/**
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "./src/Frontend/saddit-front"

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: Run build
        working-directory: src/Frontend/saddit-front
        run: yarn

      - name: Run Tests
        working-directory: src/Frontend/saddit-front
        run: yarn test
