name: Daily ZAP scanner

# Controls when the workflow will run
on:
  schedule:
    - cron: 0 13 * * 1

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: "http://20.54.89.32/"
          rules_file_name: ".zap/rules.tsv"
          cmd_options: "-a"
